// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qhbqjncvlqtckblqlsgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFoYnFqbmN2bHF0Y2tibHFsc2dxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MTg3NzAsImV4cCI6MjA3MTM5NDc3MH0.PGG3qS5xb8NrFWGHggnF2MfO8zuqeEJUYMJ_6EA2NfY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});